name: Run Docker Container and Tests

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: true
        default: 'linux'
      waitTime:
        description: 'Wait time'
        required: false
        default: '20'
      downloadWaitTime:
        description: 'Download wait time'
        required: false
        default: '10'
      logLevel:
        description: 'Log level'
        required: false
        default: 'INFO'
      resolution:
        description: 'Resolution'
        required: false
        default: 'desktop'
      browsers:
        description: 'Browsers'
        required: false
        default: 'chrome,firefox'
      parallel:
        description: 'Parallel execution'
        required: false
        default: 'false'
      parallelThreads:
        description: 'Number of parallel threads'
        required: false
        default: '4'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false

      - name: Modify conf.properties
        run: |
          echo "os=${{ github.event.inputs.os }}" >> ./src/test/resources/conf.properties
          echo "waitTime=${{ github.event.inputs.waitTime }}" >> ./src/test/resources/conf.properties
          echo "downloadWaitTime=${{ github.event.inputs.downloadWaitTime }}" >> ./src/test/resources/conf.properties
          echo "log.level=${{ github.event.inputs.logLevel }}" >> ./src/test/resources/conf.properties
          echo "resolution.${{ github.event.inputs.resolution }}" >> ./src/test/resources/conf.properties
          echo "browsers={${{ github.event.inputs.browsers }}}" >> ./src/test/resources/conf.properties
          echo "parallel=${{ github.event.inputs.parallel }}" >> ./src/test/resources/conf.properties
          echo "parallel.threads=${{ github.event.inputs.parallelThreads }}" >> ./src/test/resources/conf.properties

      - name: Run Docker Container
        run: docker run --name cukefm-container cukefm-docker-image

      - name: Copy reports from container
        run: docker cp cukefm-container:/CUKEFW/src/test/resources/reports ./reports

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./reports
