name: Build and Run Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      waitTime:
        description: 'Wait Time'
        required: false
        default: '20'
      downloadWaitTime:
        description: 'Download Wait Time'
        required: false
        default: '10'
      browsers:
        description: 'Browsers'
        required: false
        default: 'chrome,firefox'
      resolution:
        description: 'Resolutions'
        required: false
        default: 'desktop'

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Override properties
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "waitTime=${{ github.event.inputs.waitTime }}" >> src/test/resources/conf.properties
          echo "downloadWaitTime=${{ github.event.inputs.downloadWaitTime }}" >> src/test/resources/conf.properties
          echo "browsers={${{ github.event.inputs.browsers }}}" >> src/test/resources/conf.properties
          echo "resolutions={${{ github.event.inputs.resolution }}}" >> src/test/resources/conf.properties

      - name: Build and run tests
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: cukefm-docker-image:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run tests in Docker container
        run: docker run --name cukefm-container cukefm-docker-image:latest

      - name: Copy results from container
        run: docker cp cukefm-container:CUKEFW/src/test/resources/reports ./reports

      - name: Remove container
        run: docker stop cukefm-container && docker rm cukefm-container

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./reports
